version: '3.8'
author: SeaHuyty

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5173:80"
    depends_on:
      - backend
